# Generated by Django 5.1 on 2024-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('artist', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('spotify_artist_id', models.CharField(max_length=100)),
                ('ticketmaster_event_id', models.CharField(max_length=100)),
            ],
        ),
    ]
